"""add_user_module_permissions

Revision ID: c44c79069f49
Revises: 0006_add_hide_sql_queries
Create Date: 2026-06-20 01:38:48.281571+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c44c79069f49'
down_revision: str | None = '0006_add_hide_sql_queries'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('module_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'module_permissions')
    # ### end Alembic commands ###
